### ISSUE TITLE
Create basic page with immutable todo list

### ISSUE THREAD

**Issue by alex-on-java** [alex-on-java/testme#1]
## Why
We need something working for the beginning. 

## User story
**As** Product manager
**I want** to see the page with dummy todo list 
**so that** I could have the start point for the development.

## Acceptance criteria 
 - [x] I could open page in browser for adress live.testme.buyanov.ru
 - [x] This page is accessible for everyone
 - [x] This page works in all main browsers and platforms (including mobile)

**Comment by alex-on-java** [comment]
http://e1.dev.testme.buyanov.ru - could be tested here

**Comment by AlenkaaPr** [comment]
I cannot run Test Suit [#1](https://github.com/alex-on-java/testme/blob/master/testing/TBD1.md)

The APP did not open in browsers:

- Google  Chrome 67 
 - Microsoft IE9
- Microsoft Edge
- Mozilla Fierfox 60
- MAC Safary 10
- Chrome-mibile 67
- MAC Safary-mobile 10

**Comment by alex-on-java** [comment]
@AlenkaaPr should work

**Comment by AlenkaaPr** [comment]
Test Suit  [#1](https://github.com/alex-on-java/testme/blob/master/testing/TBD1.md)
ALL test cases are passed.

**Comment by alex-on-java** [comment]
@AlenkaaPr you need to test on http://staging.testme.buyanov.ru

**Comment by AlenkaaPr** [comment]
Test Suit [#1](https://github.com/AlenkaaPr/testme/blob/master/testing/TBD1.md)
All test cases are passed

**Comment by alex-on-java** [comment]
Deployed live
