### ISSUE TITLE
User could add new item to todo list

### ISSUE THREAD

**Issue by alex-on-java** [alex-on-java/testme#10]
## Why
We want to add some interaction to the app

## User story
**As** User
**I want** to add elements to the todo list 
**so that** I could create my own todo list.

## Acceptance criteria 
 - [ ] The initial list is still there
 - [ ] There is an input field with a button with the label "Add"
 - [ ] Once you put something into the input filed and press the button, a new element appears at the end of the todo list. The text of the item is the same as was entered
 - [ ] Once you reload the page, you see that all elements are in place
 - [ ] If item successfully added, input field should be cleared 

### Aditional information 
No need to save the data once the server is reloaded

**Comment by alex-on-java** [comment]
Implemented here:  http://e2.dev.testme.buyanov.ru
